[package]
name = "mima-common"
version = "0.1.0"
authors = ["JohnnyJayJay <johnnyjayjay02@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.20"
strum_macros = "0.20.1"
enum-repr = "0.2.6"
byteorder = "1.3.4"

